export const DONATION_STATUSES = [
  'AVAILABLE',
  'CLAIMED',
  'PICKUP_PENDING',
  'COLLECTED',
  'COMPLETED',
  'EXPIRED',
  'CANCELLED',
];

export const DONATION_STATUS_LABELS = {
  AVAILABLE: 'Available',
  CLAIMED: 'Claimed',
  PICKUP_PENDING: 'Pickup Pending',
  COLLECTED: 'Collected',
  COMPLETED: 'Completed',
  EXPIRED: 'Expired',
  CANCELLED: 'Cancelled',
};

export const DONATION_CATEGORIES = [
  'Cooked Meals',
  'Bakery & Snacks',
  'Fresh Produce',
  'Packaged Food',
  'Beverages',
];

export const MOCK_DONATIONS = [
  {
    id: 'FD001',
    name: 'Vegetable biryani & dal',
    quantity: '45 meal portions',
    quantityValue: 45,
    unit: 'portions',
    category: 'Cooked Meals',
    dietary: 'Vegetarian',
    status: 'PICKUP_PENDING',
    preparedAt: 'Today, 11:30 AM',
    consumeBefore: 'Today, 5:30 PM',
    pickupDate: 'Today',
    pickupWindow: '2:00 PM – 3:00 PM',
    location: 'Central Hostel Dining Hall',
    storage: 'Hot-held above 60°C until collection',
    allergens: 'Contains dairy',
    description: 'Freshly prepared lunch portions packed for safe handover.',
    claimant: 'Hope Community Kitchen',
    claimantNote: 'Pickup coordinator assigned',
    impact: '45 meals kept in circulation',
    postedAt: 'Today, 12:05 PM',
  },
  {
    id: 'FD002',
    name: 'Assorted sandwich boxes',
    quantity: '28 boxes',
    quantityValue: 28,
    unit: 'boxes',
    category: 'Packaged Food',
    dietary: 'Vegetarian & Non-Vegetarian',
    status: 'AVAILABLE',
    preparedAt: 'Today, 9:15 AM',
    consumeBefore: 'Today, 7:00 PM',
    pickupDate: 'Today',
    pickupWindow: '4:00 PM – 5:00 PM',
    location: 'Campus Events Pantry',
    storage: 'Refrigerated at 4°C',
    allergens: 'Contains wheat, dairy; assorted fillings',
    description: 'Individually packed sandwiches from a cancelled campus event.',
    claimant: '',
    claimantNote: 'Awaiting an NGO pickup request',
    impact: '28 boxes available for redistribution',
    postedAt: 'Today, 9:45 AM',
  },
  {
    id: 'FD003',
    name: 'Bananas and seasonal fruit',
    quantity: '18 kg',
    quantityValue: 18,
    unit: 'kg',
    category: 'Fresh Produce',
    dietary: 'Vegetarian',
    status: 'CLAIMED',
    preparedAt: 'Yesterday, 4:00 PM',
    consumeBefore: 'Tomorrow, 12:00 PM',
    pickupDate: 'Today',
    pickupWindow: '1:00 PM – 2:00 PM',
    location: 'North Gate Stores',
    storage: 'Cool, dry produce storage',
    allergens: 'None declared',
    description: 'Ripe seasonal fruit that is ready for same-day distribution.',
    claimant: 'Neighbourhood Food Collective',
    claimantNote: 'Claim confirmed; pickup window reserved',
    impact: '18 kg of produce redirected',
    postedAt: 'Yesterday, 4:20 PM',
  },
  {
    id: 'FD004',
    name: 'Dinner rolls and pastries',
    quantity: '64 pieces',
    quantityValue: 64,
    unit: 'pieces',
    category: 'Bakery & Snacks',
    dietary: 'Vegetarian',
    status: 'COMPLETED',
    preparedAt: '18 Sep 2026, 3:00 PM',
    consumeBefore: '19 Sep 2026, 12:00 PM',
    pickupDate: '19 Sep 2026',
    pickupWindow: '10:00 AM – 11:00 AM',
    location: 'Central Hostel Dining Hall',
    storage: 'Covered bakery storage',
    allergens: 'Contains wheat, eggs, dairy',
    description: 'Bakery surplus collected following the evening service.',
    claimant: 'Hope Community Kitchen',
    claimantNote: 'Collection recorded by donor team',
    impact: '64 bakery items redistributed',
    postedAt: '18 Sep 2026, 4:10 PM',
  },
  {
    id: 'FD005',
    name: 'Lentil soup containers',
    quantity: '22 containers',
    quantityValue: 22,
    unit: 'containers',
    category: 'Cooked Meals',
    dietary: 'Vegetarian',
    status: 'COLLECTED',
    preparedAt: '16 Sep 2026, 5:30 PM',
    consumeBefore: '16 Sep 2026, 10:00 PM',
    pickupDate: '16 Sep 2026',
    pickupWindow: '7:00 PM – 8:00 PM',
    location: 'South Campus Kitchen',
    storage: 'Hot-held until collection',
    allergens: 'None declared',
    description: 'Portioned soup collected during the evening pickup window.',
    claimant: 'Neighbourhood Food Collective',
    claimantNote: 'Collected and transferred to receiving organization',
    impact: '22 servings kept out of waste',
    postedAt: '16 Sep 2026, 5:50 PM',
  },
  {
    id: 'FD006',
    name: 'Event fruit cups',
    quantity: '36 cups',
    quantityValue: 36,
    unit: 'cups',
    category: 'Fresh Produce',
    dietary: 'Vegetarian',
    status: 'EXPIRED',
    preparedAt: '12 Sep 2026, 10:00 AM',
    consumeBefore: '12 Sep 2026, 3:00 PM',
    pickupDate: '12 Sep 2026',
    pickupWindow: '1:00 PM – 2:00 PM',
    location: 'Campus Events Pantry',
    storage: 'Refrigerated at 4°C',
    allergens: 'None declared',
    description: 'Listing expired after the safe consumption window elapsed.',
    claimant: '',
    claimantNote: 'No collection recorded',
    impact: 'Listing closed after safety window',
    postedAt: '12 Sep 2026, 10:15 AM',
  },
  {
    id: 'FD007',
    name: 'Rice and vegetable curry',
    quantity: '30 meal portions',
    quantityValue: 30,
    unit: 'portions',
    category: 'Cooked Meals',
    dietary: 'Vegetarian',
    status: 'CANCELLED',
    preparedAt: '10 Sep 2026, 11:00 AM',
    consumeBefore: '10 Sep 2026, 4:00 PM',
    pickupDate: '10 Sep 2026',
    pickupWindow: '1:30 PM – 2:30 PM',
    location: 'Central Hostel Dining Hall',
    storage: 'Hot-held until handover',
    allergens: 'Contains dairy',
    description: 'Listing cancelled after the donor adjusted its service quantities.',
    claimant: '',
    claimantNote: 'Cancelled by donor before collection',
    impact: 'Listing closed by donor',
    postedAt: '10 Sep 2026, 11:20 AM',
  },
];

export const DONOR_PROFILE = {
  name: 'Central Hostel & Canteen',
  type: 'Food Donor',
  email: 'canteen@campus.edu',
  phone: '+91 98765 43210',
  address: 'Central Campus, Main Dining Block',
  pickupNotes: 'Collection point is beside the north service entrance. Please call the dining desk on arrival.',
  joined: 'September 2026',
  contactPerson: 'Ananya Rao',
};

export const DONOR_STATS = [
  { title: 'Active Donations', value: '3', description: 'illustrative value' },
  { title: 'Meals Rescued', value: '1,248', description: 'illustrative value' },
  { title: 'Donations Completed', value: '18', description: 'illustrative value' },
  { title: 'Food Diverted', value: '286 kg', description: 'illustrative value' },
];

export const DONOR_ACTIVITY = [
  { label: 'Donation posted', detail: 'Vegetable biryani & dal', time: 'Today, 12:05 PM', tone: 'primary' },
  { label: 'Donation claimed', detail: 'Bananas and seasonal fruit · Neighbourhood Food Collective', time: 'Yesterday, 4:35 PM', tone: 'info' },
  { label: 'Pickup pending', detail: 'Vegetable biryani & dal · 2:00 PM – 3:00 PM', time: 'Today', tone: 'warning' },
  { label: 'Donation completed', detail: 'Dinner rolls and pastries · 64 pieces', time: '19 Sep 2026', tone: 'success' },
];

export function getDonationById(id) {
  return MOCK_DONATIONS.find((donation) => donation.id === id) || MOCK_DONATIONS[0];
}
