import React, { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, MapPin, Package, ShieldCheck, Users } from 'lucide-react';
import { PageContent } from '@/components/common/PageContent';
import { PageHeader } from '@/components/common/PageHeader';
import { Button } from '@/components/common/Button';
import { Card } from '@/components/cards/Card';
import { StatusBadge } from '@/components/data-display/StatusBadge';
import { Modal } from '@/components/feedback/Modal';
import { useToast } from '@/components/feedback';
import { NGO_FOOD_STATUS_LABELS, getClaimForFood, getNgoFoodById } from '@/constants/ngoData';

export function FoodDetailsPage() {
  const { donationId } = useParams();
  const donation = getNgoFoodById(donationId);
  const existingClaim = getClaimForFood(donation.id);
  const toast = useToast();
  const [showClaimModal, setShowClaimModal] = useState(false);
  const [claimStatus, setClaimStatus] = useState(existingClaim?.status || donation.status);
  const isAvailable = claimStatus === 'AVAILABLE';
  const handleClaim = () => { setClaimStatus('CLAIMED'); setShowClaimModal(false); toast.success('This prototype claim is shown locally only; no donor or backend was contacted.', 'Claim simulated'); };
  return (
    <PageContent>
      <PageHeader breadcrumbs={<Link to="/ngo/available-food" className="inline-flex items-center gap-1.5 hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30"><ArrowLeft className="h-3.5 w-3.5" aria-hidden="true" />Back to Available Food</Link>} title={donation.name} description={`${donation.quantity} · ${donation.category} · ${donation.id}`} badge={<StatusBadge status={NGO_FOOD_STATUS_LABELS[claimStatus] || claimStatus} showIcon />} actions={isAvailable ? <Button variant="primary" onClick={() => setShowClaimModal(true)} leftIcon={<CheckCircle2 className="h-4 w-4" aria-hidden="true" />}>Claim Donation</Button> : <StatusBadge status={NGO_FOOD_STATUS_LABELS[claimStatus] || claimStatus} showIcon />} />
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(300px,0.8fr)]">
        <div className="space-y-6">
          <Card padding="lg"><div className="grid gap-6 md:grid-cols-[180px_minmax(0,1fr)]"><div className="flex min-h-44 items-center justify-center rounded-xl border border-dashed border-border bg-surface-muted text-center"><div className="px-4"><Package className="mx-auto h-8 w-8 text-text-muted" aria-hidden="true" /><p className="mt-3 text-xs font-semibold text-text-secondary">No photo attached</p><p className="mt-1 text-[11px] leading-relaxed text-text-muted">Donor image placeholder</p></div></div><div><p className="text-xs font-semibold uppercase tracking-wider text-text-muted">Donation overview</p><h2 className="mt-2 text-xl font-bold text-text-primary">{donation.name}</h2><p className="mt-2 text-sm leading-relaxed text-text-secondary">{donation.description}</p><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-text-muted">Donor organization</dt><dd className="mt-1 text-sm font-semibold text-text-primary">{donation.donor}</dd></div><div><dt className="text-xs text-text-muted">Quantity</dt><dd className="mt-1 text-sm font-semibold text-text-primary">{donation.quantity}</dd></div><div><dt className="text-xs text-text-muted">Dietary profile</dt><dd className="mt-1 text-sm font-semibold text-text-primary">{donation.dietary}</dd></div><div><dt className="text-xs text-text-muted">Donor type</dt><dd className="mt-1 text-sm font-semibold text-text-primary">{donation.donorType}</dd></div></dl></div></div></Card>
          <Card padding="lg"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" aria-hidden="true" /><h2 className="text-base font-bold text-text-primary">Food safety information</h2></div><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-text-muted">Prepared time</dt><dd className="mt-1 text-sm font-semibold text-text-primary">{donation.preparedAt}</dd></div><div><dt className="text-xs text-text-muted">Consume before</dt><dd className="mt-1 text-sm font-semibold text-text-primary">{donation.consumeBefore}</dd></div><div><dt className="text-xs text-text-muted">Storage condition</dt><dd className="mt-1 text-sm font-semibold text-text-primary">{donation.storage}</dd></div><div><dt className="text-xs text-text-muted">Allergen information</dt><dd className="mt-1 text-sm font-semibold text-text-primary">{donation.allergens}</dd></div></dl><p className="mt-5 rounded-lg border border-border bg-surface-muted px-3 py-2 text-xs leading-relaxed text-text-secondary">Food safety information is provided by the donor. Your organization should assess suitability before accepting or distributing food.</p></Card>
          <Card padding="lg"><div className="flex items-center gap-2"><MapPin className="h-5 w-5 text-primary" aria-hidden="true" /><h2 className="text-base font-bold text-text-primary">Pickup information</h2></div><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-text-muted">Pickup location</dt><dd className="mt-1 text-sm font-semibold text-text-primary">{donation.location}</dd></div><div><dt className="flex items-center gap-1.5 text-xs text-text-muted"><CalendarDays className="h-3.5 w-3.5" aria-hidden="true" />Pickup date</dt><dd className="mt-1 text-sm font-semibold text-text-primary">{donation.pickupDate}</dd></div><div><dt className="flex items-center gap-1.5 text-xs text-text-muted"><Clock3 className="h-3.5 w-3.5" aria-hidden="true" />Pickup window</dt><dd className="mt-1 text-sm font-semibold text-text-primary">{donation.pickupWindow}</dd></div><div><dt className="text-xs text-text-muted">Pickup notes</dt><dd className="mt-1 text-sm font-semibold text-text-primary">{donation.pickupNotes}</dd></div></dl></Card>
        </div>
        <div className="space-y-6"><Card padding="lg"><p className="text-xs font-semibold uppercase tracking-wider text-text-muted">Donor information</p><div className="mt-4 flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-primary-light text-sm font-bold text-primary-dark">{donation.donor.slice(0, 2).toUpperCase()}</span><div><h2 className="text-base font-bold text-text-primary">{donation.donor}</h2><p className="mt-1 text-xs text-text-secondary">{donation.donorType}</p><p className="mt-3 inline-flex items-center gap-1.5 text-xs text-text-secondary"><Users className="h-3.5 w-3.5 text-primary" aria-hidden="true" />Verified network participant</p></div></div></Card><Card variant="subtle" padding="lg"><p className="text-xs font-semibold uppercase tracking-wider text-text-muted">Claim status</p><h2 className="mt-2 text-lg font-bold text-text-primary">{isAvailable ? 'Available to request' : NGO_FOOD_STATUS_LABELS[claimStatus] || claimStatus}</h2><p className="mt-2 text-xs leading-relaxed text-text-secondary">{isAvailable ? 'Claiming reserves this listing for your organization in this local prototype.' : 'This listing is no longer available for a new claim in the current prototype state.'}</p>{isAvailable && <Button className="mt-5 w-full" variant="primary" onClick={() => setShowClaimModal(true)}>Claim Donation</Button>}</Card></div>
      </div>
      <Modal isOpen={showClaimModal} onClose={() => setShowClaimModal(false)} title="Claim this donation?" description="This is a frontend-only prototype interaction." footer={<><Button variant="outline" onClick={() => setShowClaimModal(false)}>Cancel</Button><Button variant="primary" onClick={handleClaim}>Confirm Claim</Button></>}><p className="text-sm leading-relaxed text-text-secondary">You are requesting <strong className="font-semibold text-text-primary">{donation.quantity}</strong> of <strong className="font-semibold text-text-primary">{donation.name}</strong> from {donation.donor}.</p><p className="mt-4 rounded-lg border border-border bg-surface-muted px-3 py-2 text-xs leading-relaxed text-text-secondary">No donor will be contacted and no backend record will be created. The status will update locally so you can review the prototype flow.</p></Modal>
    </PageContent>
  );
}
export default FoodDetailsPage;
