import React from 'react';
import { Link } from 'react-router-dom';
import { BarChart3, CheckCircle2, ClipboardList, Package, ShieldCheck, Users, ArrowRight } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { PageContent } from '@/components/common/PageContent';
import { PageHeader } from '@/components/common/PageHeader';
import { PageSection } from '@/components/common/PageSection';
import { Button } from '@/components/common/Button';
import { Card } from '@/components/cards/Card';
import { StatCard } from '@/components/cards/StatCard';
import { AdminActivityList, AdminChartCard, AdminStatus } from '@/components/admin';
import { ADMIN_STATS, ADMIN_ACTIVITY, ADMIN_DONATIONS, DONATION_STATUS_BREAKDOWN, DONATION_TREND } from '@/constants/adminData';

const statIcons = [Users, Users, ShieldCheck, Package, CheckCircle2, ClipboardList, BarChart3, CheckCircle2];
export default function AdminDashboard() {
  return <PageContent spacing="loose">
    <PageHeader title="Admin Dashboard" description="Monitor FoodBridge activity, users, donations, and redistribution impact." badge={<span className="rounded-full border border-primary/20 bg-primary-light px-2.5 py-1 text-xs font-semibold text-primary-dark">Demo control center</span>} actions={<Button asChild variant="outline" size="sm" rightIcon={<ArrowRight className="h-3.5 w-3.5" />}><Link to="/admin/reports">View reports</Link></Button>}><p className="text-xs text-text-muted">All metrics on this page are illustrative prototype data.</p></PageHeader>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{ADMIN_STATS.map((stat, index) => <StatCard key={stat.title} {...stat} icon={statIcons[index]} variant={stat.tone === 'info' ? 'info' : stat.tone === 'warning' ? 'warning' : stat.tone === 'accent' ? 'accent' : stat.tone === 'primary' ? 'primary' : 'default'} />)}</div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(320px,0.6fr)]"><AdminChartCard title="Donation activity" description="Monthly demo donation volume and completions."><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={DONATION_TREND} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="rgba(18,55,42,0.10)" vertical={false} /><XAxis dataKey="month" tick={{ fontSize: 11, fill: '#64756B' }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 11, fill: '#64756B' }} axisLine={false} tickLine={false} /><Tooltip /><Legend iconType="circle" wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="donations" name="Posted" fill="#168A45" radius={[4, 4, 0, 0]} /><Bar dataKey="completed" name="Completed" fill="#86B83F" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></AdminChartCard><AdminChartCard title="Donation status" description="Current distribution of illustrative records."><div className="h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={DONATION_STATUS_BREAKDOWN} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={2}>{DONATION_STATUS_BREAKDOWN.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip /><Legend layout="vertical" align="right" verticalAlign="middle" iconType="circle" wrapperStyle={{ fontSize: 10 }} /></PieChart></ResponsiveContainer></div></AdminChartCard></div>
    <div className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]"><Card padding="lg"><div className="mb-4 flex items-start justify-between"><div><h2 className="text-base font-bold text-text-primary">Recent activity</h2><p className="mt-1 text-xs text-text-secondary">Latest platform events in the demo feed.</p></div><Link to="/admin/reports" className="text-xs font-semibold text-primary hover:underline">Analytics</Link></div><AdminActivityList items={ADMIN_ACTIVITY} /></Card><PageSection title="Recent donations" description="A compact operational view of recently posted food." action={<Button asChild variant="outline" size="sm"><Link to="/admin/donations">View all</Link></Button>}><div className="overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-border bg-surface-muted text-[11px] uppercase tracking-wider text-text-secondary"><tr><th className="px-4 py-3">Food</th><th className="px-4 py-3">Donor</th><th className="px-4 py-3">Quantity</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-border/70">{ADMIN_DONATIONS.slice(0, 4).map((donation) => <tr key={donation.id}><td className="px-4 py-3"><p className="font-semibold text-text-primary">{donation.name}</p><p className="text-xs text-text-muted">{donation.location}</p></td><td className="px-4 py-3 text-xs text-text-secondary">{donation.donor}</td><td className="px-4 py-3 text-xs text-text-secondary">{donation.quantity}</td><td className="px-4 py-3"><AdminStatus status={donation.status} /></td><td className="px-4 py-3 text-right"><Link to={`/admin/donations/${donation.id}`} className="text-xs font-semibold text-primary hover:underline">View</Link></td></tr>)}</tbody></table></div></PageSection></div>
  </PageContent>;
}
